### ISSUE TITLE
Sporadische Fehlermeldung - Was ist die Ursache?

### ISSUE THREAD

**Issue by LK1976** [Apollon77/ioBroker.homekit-controller#265]
Hallo Zusammen,

ich nutze den HomKit-Controller in der Version 0.5.7 und erhalte sporadisch immer mal wieder folgende Fehlermeldungen:

![grafik](https://user-images.githubusercontent.com/121298651/218312646-7707a925-ccc8-4b54-ad99-f6d123c4226e.png)

Letztendlich scheint der Fehler nicht von Dauer zu sein, denn nach einer gewissen Zeit reinitialisiert sich die Verbindung von alleine. Während des Fehlers ist das Objekt nicht schaltbar. Was sind die Gründe für den Fehler? Wie kann ich das Problem abstellen?

**Comment by Apollon77** [comment]
Der Fehler bedeutet das das Gerä tauf eine Abfrage der Daten nicht reagiert hat. nach 5 versuchen gibt der Adapter auf und initialisiert die Verbindung neu. Um zu sehen was ggf der Auslöser ist, ist mehr Log interessant ... wenn es regelmäßig kommt, ggf mal Debug log aktivieren und dann großzügig Log hier posten.

**Comment by LK1976** [comment]
Hilft dieser Debug-Log weiter:


2023-02-12 10:46:17.987  - [32minfo[39m: homekit-controller.0 (49949) IP-9F:BA:89:07:32:EF Resubscribe not successful, reinitialize device
2023-02-12 10:46:21.058  - [32minfo[39m: homekit-controller.0 (49949) IP-9F:BA:89:07:32:EF Resubscribe not successful, reinitialize device
2023-02-12 10:46:24.132  - [32minfo[39m: homekit-controller.0 (49949) IP-9F:BA:89:07:32:EF Resubscribe not successful, reinitialize device
2023-02-12 10:46:27.201  - [32minfo[39m: homekit-controller.0 (49949) IP-9F:BA:89:07:32:EF Resubscribe not successful, reinitialize device
2023-02-12 10:47:09.137  - [32minfo[39m: homekit-controller.0 (49949) Device IP-9F:BA:89:07:32:EF data polling failed (1): Timeout
2023-02-12 10:48:18.004  - [33mwarn[39m: homekit-controller.0 (49949) IP-9F:BA:89:07:32:EF Could not initialize device:  TimeoutError
    at Object.<anonymous> (/opt/iobroker/node_modules/@esm2cjs/p-queue/build/cjs/index.js:51:22)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js:43:35)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
2023-02-12 10:49:39.140  - [32minfo[39m: homekit-controller.0 (49949) Device IP-9F:BA:89:07:32:EF data polling failed (2): Timeout
2023-02-12 10:52:09.142  - [32minfo[39m: homekit-controller.0 (49949) Device IP-9F:BA:89:07:32:EF data polling failed (3): Timeout
2023-02-12 10:54:39.145  - [32minfo[39m: homekit-controller.0 (49949) Device IP-9F:BA:89:07:32:EF data polling failed (4): Timeout
2023-02-12 10:54:39.146  - [33mwarn[39m: homekit-controller.0 (49949) Device IP-9F:BA:89:07:32:EF had too many errors, reinitialize connection
2023-02-12 13:32:02.053  - [32minfo[39m: homekit-controller.0 (49949) IP-9F:BA:89:07:32:EF Resubscribe not successful, reinitialize device
2023-02-12 13:32:05.126  - [32minfo[39m: homekit-controller.0 (49949) IP-9F:BA:89:07:32:EF Resubscribe not successful, reinitialize device
2023-02-12 13:32:08.198  - [32minfo[39m: homekit-controller.0 (49949) IP-9F:BA:89:07:32:EF Resubscribe not successful, reinitialize device
2023-02-12 13:32:11.266  - [32minfo[39m: homekit-controller.0 (49949) IP-9F:BA:89:07:32:EF Resubscribe not successful, reinitialize device
2023-02-12 13:32:14.336  - [32minfo[39m: homekit-controller.0 (49949) IP-9F:BA:89:07:32:EF Resubscribe not successful, reinitialize device
2023-02-12 13:34:02.097  - [33mwarn[39m: homekit-controller.0 (49949) IP-9F:BA:89:07:32:EF Could not initialize device:  TimeoutError
    at Object.<anonymous> (/opt/iobroker/node_modules/@esm2cjs/p-queue/build/cjs/index.js:51:22)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js:43:35)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
2023-02-12 13:35:36.283  - [32minfo[39m: homekit-controller.0 (49949) Device IP-9F:BA:89:07:32:EF data polling failed (2): Timeout
2023-02-12 13:38:06.284  - [32minfo[39m: homekit-controller.0 (49949) Device IP-9F:BA:89:07:32:EF data polling failed (3): Timeout
2023-02-12 13:40:36.287  - [32minfo[39m: homekit-controller.0 (49949) Device IP-9F:BA:89:07:32:EF data polling failed (4): Timeout
2023-02-12 13:40:36.288  - [33mwarn[39m: homekit-controller.0 (49949) Device IP-9F:BA:89:07:32:EF had too many errors, reinitialize connection

**Comment by Apollon77** [comment]
Sorry, da ist kein Debug drin :-)
Debug log: Admin -> Expertenmodus -> Instanzen - instanz aufklappen -> Loglevel ändern. Adapter startet neu. Dann Log vom Logfile auf Platte unter /opt/iobroker/log ... nehmen

**Comment by LK1976** [comment]
Jetzt habe ich aber hoffentlich einen aussagekräftigen Log:

[iobroker.2023-02-21.log](https://github.com/Apollon77/ioBroker.homekit-controller/files/10798351/iobroker.2023-02-21.log)

@Apollon77: Kannst Du die Ursache finden, warum es hier zu Fehlermeldungen "had too many errors, reinitialize connection" kommt?

**Comment by LK1976** [comment]
@Apollon77 Seit ein paar Tagen bekomme ich die Instanz des Homekit-Controller nicht mehr auf grün (rot bei "Verbunden mit Gerät oder Dienst). Nach einem Neustart wird u. a. folgendes protokolliert:

![grafik](https://user-images.githubusercontent.com/121298651/224482551-f38c4bae-f677-4fb7-9b44-2a9f406751c1.png)

Oder etwas detaillierter hier:

[iobroker.2023-03-11.log](https://github.com/Apollon77/ioBroker.homekit-controller/files/10948414/iobroker.2023-03-11.log)

Ich habe an der Konfiguration des ioBrokers nichts geändert, so dass ich keine Erklärung dafür habe, warum nun die Instanz nicht mehr auf "grün" springt. Apollon77, kannst Du mir bitte einen Tipp geben, wie ich das Problem behebe? Ein Update des Adapters von Version 0.5.7 auf 0.5.8 brachte keine Verbesserung.

**Comment by Apollon77** [comment]
Die Steckdose mal Stromlos gemacht? Fakt ist das der Adapter versucht Sie auf IP und Port (siehe log) die sie selbst announced zu verbinden aber dann innerhalb von 2s keine Antwort bekommt. Ggf mal versuchen zu resetten und neu zu pairen.

**Comment by LK1976** [comment]
Kurzzeitiges Stromlosmachen der Steckdose war die Lösung. Danke! 😉

**Comment by Apollon77** [comment]
Tja die "IT support weissheiten" bewahrheiten sich doch immer wieder mal :-)
