### ISSUE TITLE
Instanz is terminating itself

### ISSUE THREAD

**Issue by Draygv2** [Apollon77/ioBroker.homekit-controller#291]
**Describe the bug**  
Because of many error during the start the instanz stop running.

**To Reproduce**  
1. Run Instanz
2. See error

**Expected behavior**  
Running normal

**Screenshots & Logfiles**  
`<html>
<body>

2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
--
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[0]: Error: undefined is not a valid state value
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[0]: at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/maybeCallback.ts:136:17)
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[0]: at HomekitController._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7594:26)
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[0]: at HomekitController.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7552:21)
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js:745:26
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[0]: at Array.forEach ()
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[0]: at HomekitController.setCharacteristicValues (/opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js:734:32)
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[0]: at Timeout. (/opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js:702:30)
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[0]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[1]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[1]: Error: undefined is not a valid state value
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[1]: at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/maybeCallback.ts:136:17)
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[1]: at HomekitController._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7594:26)
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[1]: at HomekitController.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7552:21)
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js:745:26
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[1]: at Array.forEach ()
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[1]: at HomekitController.setCharacteristicValues (/opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js:734:32)
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[1]: at Timeout. (/opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js:702:30)
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[1]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[2]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[3]: Error: undefined is not a valid state value
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[3]: at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/maybeCallback.ts:136:17)
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[3]: at HomekitController._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7594:26)
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[3]: at HomekitController.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7552:21)
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[3]: at /opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js:745:26
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[3]: at Array.forEach ()
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[3]: at HomekitController.setCharacteristicValues (/opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js:734:32)
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[3]: at Timeout. (/opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js:702:30)
2023-09-20 06:43:35.544 - error: host.Iobroker-prod Caught by controller[3]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: Error: undefined is not a valid state value
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/maybeCallback.ts:136:17)
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: at HomekitController._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7594:26)
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: at HomekitController.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7552:21)
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: at /opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js:745:26
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: at Array.forEach ()
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: at HomekitController.setCharacteristicValues (/opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js:734:32)
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: at Timeout. (/opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js:702:30)
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: Error: undefined is not a valid state value
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/maybeCallback.ts:136:17)
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: at HomekitController._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7594:26)
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: at HomekitController.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7552:21)
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: at /opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js:745:26
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: at Array.forEach ()
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: at HomekitController.setCharacteristicValues (/opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js:734:32)
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: at Timeout. (/opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js:702:30)
2023-09-20 06:43:35.545 - error: host.Iobroker-prod Caught by controller[4]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-20 06:43:35.545 - error: host.Iobroker-prod instance system.adapter.homekit-controller.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

</body>
</html>`

`<html>
<body>

2023-09-20 06:43:35.002 - error: homekit-controller.0 (45777) undefined is not a valid state value
--
2023-09-20 06:43:35.006 - error: homekit-controller.0 (45777) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-09-20 06:43:35.006 - error: homekit-controller.0 (45777) unhandled promise rejection: undefined is not a valid state value
2023-09-20 06:43:35.006 - error: homekit-controller.0 (45777) Error: undefined is not a valid state value

</body>
</html>`

![image](https://github.com/Apollon77/ioBroker.homekit-controller/assets/62559741/0833db95-97d8-4c94-a34b-15a7b340298a)

**Versions:**  
 - Adapter version: <v0.5.8>
 - JS-Controller version: <5.0.12> 
 - Node version: <18.17.1> 
 - Operating system: <Ubuntu>

**Comment by Apollon77** [comment]
Please enable debug logging and provide a debug log. Thank you

**Comment by Draygv2** [comment]
Thanks for the quick respond
[Homekit-problem.txt](https://github.com/Apollon77/ioBroker.homekit-controller/files/12670221/Homekit-problem.txt)

**Comment by mac89muc** [comment]
Hello, I've exactly the same issue since the js-controller update to 5.0.12 with Adapter Version 0.5.8.

@Apollon77 do you need a second debug log?

**Comment by Apollon77** [comment]
ne alles gut. Da sind einzelne States die da reported werden kein Wert sondern haben einen Fehlerstatus. Ich schaue mal

**Comment by Apollon77** [comment]
Please try GitHub version

**Comment by mac89muc** [comment]
@Apollon77  - Danke für's schnelle kümmern.
Schon regulär über Adapter -> GitHub Katze -> von Github installieren und dort den Adapter aus dem dropdown raussuchen, oder? nicht per Benutzerdefiniert mit der URL zum Adapter hier bei Git?

Bei der ersten Variante wird mir nach wie vor nur der 0.5.8 angeboten, der schon installiert war.

**Comment by Draygv2** [comment]
@Apollon77 it's running till now.
Many thanks for the quick fix.
@mac89muc auf die Katze Adapter auswählen und installieren.

**Comment by mac89muc** [comment]
@Draygv2 - Danke, so habe ich es wie gesagt probiert - ist bei mir noch immer die 0.5.8. Welche Version hast Du jetzt bei der GitVersion?

**Comment by Draygv2** [comment]
Die Version ist die gleiche funktioniert aber trotzdem.

**Comment by Apollon77** [comment]
versionsnummer ist gleich, müsst die instanz nur nach Update einmalig  neu starten

**Comment by mac89muc** [comment]
Dann passt es - dachte da gäbe es dann eine neue Versionsnummer.
Die Github-Version produziert bisher auch keine Fehler im Log bei mir - Danke.

**Comment by Apollon77** [comment]
Neue version erst wenn ich release. Alpha Tests via Github bei mir meistens mit gleicher Nummer

**Comment by mac89muc** [comment]
Leider zu früh gefreut - habe wieder Fehlermeldungen im Log und Neustarts - siehe Anhang.
Hilft das ggf. weiter...
[log.txt](https://github.com/Apollon77/ioBroker.homekit-controller/files/12706789/log.txt)

**Comment by Apollon77** [comment]
Debug log pelase.

**Comment by mac89muc** [comment]
hatte ich oben mit angehangen, oder brauchst du ein ausführlicheres? [log.txt](https://github.com/Apollon77/ioBroker.homekit-controller/files/12711996/log.txt)

Gruß

**Comment by Apollon77** [comment]
Ja bitte. bei allen fehlern ist nix von debug zu sehen. und sicherstellen das es wirklich dei GitHub version ist!

**Comment by mac89muc** [comment]
Hab nochmal alles neugestartet, upgedated usw bisher läuft es wieder ohne Fehler. Danke
