### ISSUE TITLE
Upgrade 0.5.8 to 0.5.9 fails

### ISSUE THREAD

**Issue by AhzurdanGit** [Apollon77/ioBroker.homekit-controller#311]
While trying to upgrade (iob - latest version, latest npm, node, etc) system throws errors.

iobroker npm ERR! code 1npm ERR! path /opt/iobroker/node_modules/@abandonware/noblenpm ERR! command failednpm ERR! command sh -c node-gyp-buildnpm ERR! make: Entering directory '/opt/iobroker/node_modules/@abandonware/noble/build'npm ERR! SOLINK_MODULE(target) Release/obj.target/noble.nodenpm ERR! make: Leaving directory '/opt/iobroker/node_modules/@abandonware/noble/build'npm ERR! gyp info it worked if it ends with oknpm ERR! gyp info using node-gyp@10.0.1npm ERR! gyp info using node@20.10.0 | linux | x64npm ERR! gyp info find Python using Python version 3.11.6 found at "/usr/bin/python3"npm ERR! gyp info spawn /usr/bin/python3npm ERR! gyp info spawn args [npm ERR! gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',npm ERR! gyp info spawn args 'binding.gyp',npm ERR! gyp info spawn args '-f',npm ERR! gyp info spawn args 'make',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/opt/iobroker/node_modules/@abandonware/noble/build/config.gypi',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/home/iobroker/.cache/node-gyp/20.10.0/include/node/common.gypi',npm ERR! gyp info spawn args '-Dlibrary=shared_library',npm ERR! gyp info spawn args '-Dvisibility=default',npm ERR! gyp info spawn args '-Dnode_root_dir=/home/iobroker/.cache/node-gyp/20.10.0',npm ERR! gyp info spawn args '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',npm ERR! gyp info spawn args '-Dnode_lib_file=/home/iobroker/.cache/node-gyp/20.10.0/<(target_arch)/node.lib',npm ERR! gyp info spawn args '-Dmodule_root_dir=/opt/iobroker/node_modules/@abandonware/noble',npm ERR! gyp info spawn args '-Dnode_engine=v8',npm ERR! gyp info spawn args '--depth=.',npm ERR! gyp info spawn args '--no-parallel',npm ERR! gyp info spawn args '--generator-output',npm ERR! gyp info spawn args 'build',npm ERR! gyp info spawn args '-Goutput_dir=.'npm ERR! gyp info spawn args ]npm ERR! gyp info spawn makenpm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]npm ERR! make: g++: No such file or directorynpm ERR! make: *** [noble.target.mk:22: Release/obj.target/noble.node] Error 127npm ERR! gyp ERR! build error npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)npm ERR! gyp ERR! System Linux 6.5.11-4-pvenpm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"npm ERR! gyp ERR! cwd /opt/iobroker/node_modules/@abandonware/noblenpm ERR! gyp ERR! node -v v20.10.0npm ERR! gyp ERR! node-gyp -v v10.0.1npm ERR! gyp ERR! not oknpm ERR! A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-01-09T04_27_07_224Z-debug-0.loghost.brain-iobroker Cannot install iobroker.homekit-controller@0.5.9: 1

iobroker npm ERR! command failednpm ERR! command sh -c node-gyp-buildnpm ERR! make: Entering directory '/opt/iobroker/node_modules/@abandonware/noble/build'npm ERR! SOLINK_MODULE(target) Release/obj.target/noble.nodenpm ERR! make: Leaving directory '/opt/iobroker/node_modules/@abandonware/noble/build'npm ERR! gyp info it worked if it ends with oknpm ERR! gyp info using node-gyp@10.0.1npm ERR! gyp info using node@20.10.0 | linux | x64npm ERR! gyp info find Python using Python version 3.11.6 found at "/usr/bin/python3"npm ERR! gyp info spawn /usr/bin/python3npm ERR! gyp info spawn args [npm ERR! gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',npm ERR! gyp info spawn args 'binding.gyp',npm ERR! gyp info spawn args '-f',npm ERR! gyp info spawn args 'make',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/opt/iobroker/node_modules/@abandonware/noble/build/config.gypi',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/home/iobroker/.cache/node-gyp/20.10.0/include/node/common.gypi',npm ERR! gyp info spawn args '-Dlibrary=shared_library',npm ERR! gyp info spawn args '-Dvisibility=default',npm ERR! gyp info spawn args '-Dnode_root_dir=/home/iobroker/.cache/node-gyp/20.10.0',npm ERR! gyp info spawn args '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',npm ERR! gyp info spawn args '-Dnode_lib_file=/home/iobroker/.cache/node-gyp/20.10.0/<(target_arch)/node.lib',npm ERR! gyp info spawn args '-Dmodule_root_dir=/opt/iobroker/node_modules/@abandonware/noble',npm ERR! gyp info spawn args '-Dnode_engine=v8',npm ERR! gyp info spawn args '--depth=.',npm ERR! gyp info spawn args '--no-parallel',npm ERR! gyp info spawn args '--generator-output',npm ERR! gyp info spawn args 'build',npm ERR! gyp info spawn args '-Goutput_dir=.'npm ERR! gyp info spawn args ]npm ERR! gyp info spawn makenpm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]npm ERR! make: g++: No such file or directorynpm ERR! make: *** [noble.target.mk:22: Release/obj.target/noble.node] Error 127npm ERR! gyp ERR! build error npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)npm ERR! gyp ERR! System Linux 6.5.11-4-pvenpm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"npm ERR! gyp ERR! cwd /opt/iobroker/node_modules/@abandonware/noblenpm ERR! gyp ERR! node -v v20.10.0npm ERR! gyp ERR! node-gyp -v v10.0.1npm ERR! gyp ERR! not oknpm ERR! A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-01-09T04_27_07_224Z-debug-0.log

**Comment by AhzurdanGit** [comment]
iob fix solved it...
