### ISSUE TITLE
Cant install adapter on windows

### ISSUE THREAD

**Issue by jenbenn** [Apollon77/ioBroker.homekit-controller#344]
II Cann install the homekit controller. The follwing error code is given:

**Screenshots & Logfiles**  
ERROR: Process exited with code 25

$ iobroker add homekit-controller --host WIN-89QB1GBI51D

NPM version: 10.8.2Installing iobroker.homekit-controller@0.5.10... (System call)

npm error code 1npm error path C:\ioBroker\node_modules\@abandonware\noblenpm error command failednpm error command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp-buildnpm error node:internal/child_process:421npm error throw new ErrnoException(err, 'spawn');npm error ^npm errornpm error Error: spawn EINVALnpm error at ChildProcess.spawn (node:internal/child_process:421:11)npm error at Object.spawn (node:child_process:762:9)npm error at build (C:\ioBroker\node_modules\node-gyp-build\bin.js:29:8)npm error at preinstall (C:\ioBroker\node_modules\node-gyp-build\bin.js:38:32)npm error at C:\ioBroker\node_modules\node-gyp-build\bin.js:11:7npm error at ChildProcess.exithandler (node:child_process:430:5)npm error at ChildProcess.emit (node:events:519:28)npm error at maybeClose (node:internal/child_process:1105:16)npm error at ChildProcess._handle.onexit (node:internal/child_process:305:5) {npm error errno: -4071,npm error code: 'EINVAL',npm error syscall: 'spawn'npm error }npm errornpm error Node.js v20.17.0npm error A complete log of this run can be found in: C:\WINDOWS\system32\config\systemprofile\AppData\Local\npm-cache\_logs\2024-08-23T17_25_46_591Z-debug-0.loghost.WIN-89QB1GBI51D Cannot install iobroker.homekit-controller@0.5.10: 1

ERROR: Process exited with code 25

**Versions:**  
 - Adapter version: 0.5.10
 - JS-Controller version: 6.09
 - Node version: 20.17.0
 - Operating system: windows 11

**Comment by Apollon77** [comment]
Plese try again with 0.5.11
