### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jegow** [Apollon77/ioBroker.homekit-controller#348]
I have a problem with the installation. I get the following error message:
```sh
pi@raspberrypi:~ $ iobroker add homekit-controller
NPM version: 10.7.0
Installing iobroker.homekit-controller@0.5.10... (System call)
npm error code 1
npm error path /opt/iobroker/node_modules/@abandonware/noble
npm error command failed
npm error command sh -c node-gyp-build
npm error Traceback (most recent call last):
npm error   File "/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
npm error     import gyp  # noqa: E402
npm error   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
npm error     import gyp.input
npm error   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 8, in <module>
npm error     import gyp.common
npm error   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/common.py", line 435
npm error     if CC := os.environ.get("CC_target") or os.environ.get("CC"):
npm error            ^
npm error SyntaxError: invalid syntax
npm error gyp ERR! configure error
npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
npm error gyp ERR! stack at ChildProcess.<anonymous> (/opt/iobroker/node_modules/node-gyp/lib/configure.js:317:18)
npm error gyp ERR! stack at ChildProcess.emit (node:events:517:28)
npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:292:12)
npm error gyp ERR! System Linux 5.10.103-v7l+
npm error gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/.bin/node-gyp" "rebuild"
npm error gyp ERR! cwd /opt/iobroker/node_modules/@abandonware/noble
npm error gyp ERR! node -v v18.20.4
npm error gyp ERR! node-gyp -v v10.2.0
npm error gyp ERR! not ok
```
The syntax “if CC := os.env...” is only allowed from Python 3.8 and on my system 3.7 is installed. 

```sh
pi@raspberrypi:~ $ iob info
Platform       : linux
os             : linux
Architecture   : arm
CPUs           : 4
Speed          : 1500 MHz
Model          : ARMv7 Processor rev 3 (v7l)
RAM            : 3.7 GB
System uptime  : 04:15:10
Node.js        : v18.20.4
time           : 1729448490727
timeOffset     : -120
NPM            : 10.7.0
adapters count : 544
Disk size      : 29.0 GiB
Disk free      : 18.4 GiB
```
Python 2.7 and 3.7 are installed on my system. Python 3.8 is not available with `apt install python3.8`.

**Comment by Apollon77** [comment]
Hm ... Was ist es denn für ein System und welche version? Ich denke inzwischen ist paython 3.8 eher der standard und wird wohl von nodegyp benötigt.

**Comment by jegow** [comment]
Das ist schon lange her. Auf dem System wurden zwar regelmäßig updates gemacht, aber was ursprünglich installiert wurde, kann ich gar nicht sagen. Da muss ich noch mal ran.

**Comment by jegow** [comment]
Ok. Hat ein Weile gedauert. Ich habe das gesamte System neu installiert und das Backup eingespielt. Jetzt konnte ich den Adapter installieren. Kaum macht man es richtig - funktioniert es. Immer wieder schön.
Allerdings gibt es dennoch ein kleiner Wehmutstropfen. Ich kann das HomeKit-Gerät im Adapter nicht sehen. Das Gerät ist Online, der Ping-Adapter sieht es auch. In der Handy-App ist es ebenfalls vorhanden. Es handelt sich dabei um ein Aquara FP2 (Wifi). Im Log sehe ich keine Fehlermeldung. Irgendeine Idee, was ich noch probieren kann?

**Comment by Apollon77** [comment]
Ohje, der FP2 ist ein alter bekannter ... schau mal ob vllt closed issues hier helfen https://github.com/Apollon77/ioBroker.homekit-controller/issues?q=is%3Aissue+is%3Aclosed++aqara

**Comment by jegow** [comment]
Vielleicht suche ich an der falschen Stelle. Was bedeudet denn die nicht vorhandene Verbindung:
![grafik](https://github.com/user-attachments/assets/8d7cf692-7c81-4128-9592-f66235694f4c)
```
2024-10-31 13:21:03.177  - [32minfo[39m: host.raspberrypi "system.adapter.homekit-controller.0" enabled
2024-10-31 13:21:03.813  - [32minfo[39m: host.raspberrypi instance system.adapter.homekit-controller.0 in version "0.5.10" started with pid 508357
2024-10-31 13:21:07.861  - [32minfo[39m: homekit-controller.0 (508357) starting. Version 0.5.10 in /opt/iobroker/node_modules/iobroker.homekit-controller, node: v20.18.0, js-controller: 6.0.11
```
Ich kann im Log-File nichts verdächtiges entdecken.

**Comment by Apollon77** [comment]
lade mal admin neu, das sollte nicht rot sein, dann hätte was geknallt. Gelb würde bedeuten das du einfach kein gerät verbunden hast

**Comment by Apollon77** [comment]
Falls es grün wird wenn ein Gerät verbunden ist dann ist alles ok. ...

**Comment by jegow** [comment]
Der Neustart des Gerätes bzw. des Admin hat nichts geändert. Ich weiß nicht, ob das eine Rolle spielt, aber ich den ganzen Computer neu aufgesetzt, damit ich den HomeKit Controller installieren kann. Anschließend natürlich die alte Konfiguration eingespielt. Kann es sein, dass es irgendein Problem gibt, dass dem Controller zu schaffen macht und was nicht im Log-File erscheint?

**Comment by Apollon77** [comment]
AM besten mal debug logging aktivieren und posten bitte

**Comment by jegow** [comment]
```
2024-10-31 14:05:34.512  - [32minfo[39m: host.raspberrypi instance system.adapter.homekit-controller.0 in version "0.5.10" started with pid 2301
2024-10-31 14:05:36.677  - [34mdebug[39m: homekit-controller.0 (2301) Redis Objects: Use Redis connection: 127.0.0.1:9001
2024-10-31 14:05:36.753  - [34mdebug[39m: homekit-controller.0 (2301) Objects client ready ... initialize now
2024-10-31 14:05:36.756  - [34mdebug[39m: homekit-controller.0 (2301) Objects create System PubSub Client
2024-10-31 14:05:36.758  - [34mdebug[39m: homekit-controller.0 (2301) Objects create User PubSub Client
2024-10-31 14:05:36.846  - [34mdebug[39m: homekit-controller.0 (2301) Objects client initialize lua scripts
2024-10-31 14:05:36.857  - [34mdebug[39m: homekit-controller.0 (2301) Objects connected to redis: 127.0.0.1:9001
2024-10-31 14:05:36.924  - [34mdebug[39m: homekit-controller.0 (2301) Redis States: Use Redis connection: 127.0.0.1:9000
2024-10-31 14:05:36.999  - [34mdebug[39m: homekit-controller.0 (2301) States create System PubSub Client
2024-10-31 14:05:37.002  - [34mdebug[39m: homekit-controller.0 (2301) States create User PubSub Client
2024-10-31 14:05:37.127  - [34mdebug[39m: homekit-controller.0 (2301) States connected to redis: 127.0.0.1:9000
2024-10-31 14:05:37.199  - [34mdebug[39m: homekit-controller.0 (2301) Plugin sentry Initialize Plugin (enabled=true)
2024-10-31 14:05:38.040  - [32minfo[39m: homekit-controller.0 (2301) starting. Version 0.5.10 in /opt/iobroker/node_modules/iobroker.homekit-controller, node: v20.18.0, js-controller: 6.0.11
2024-10-31 14:05:38.254  - [34mdebug[39m: homekit-controller.0 (2301) state homekit-controller.0.info.connection changed: false (ack = true)
```

**Comment by jegow** [comment]
Gibt es etwas, was ich noch ausprobieren könnte?
